[package]
name = "chem-par"
version = "0.2.0"
entrypoint = "src/lib.typ"
authors = ["James Rupert Swift",]
license = "MIT"
description = "Display chemical formulae and IUPAC nomenclature with ease"
repository = "https://github.com/jamesrswift/typst-chem-par"
keywords = ["chemistry", "IUPAC"]
exclude = [
    "assets",
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]